version: '3.9'

services:
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      DATABASE_URL: postgres://devuser:devpass@db:5432/backend_development
      POSTGRES_DB: backend_development
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app_network

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://devuser:devpass@db:5432/backend_development
      REDIS_URL: redis://redis:6379/0
      RAILS_MASTER_KEY: 0ee296666c5c223a0aaa96e9e0b007fb
      RAILS_ENV: development
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - app_network

  sidekiq:
    build: ./backend
    command: bundle exec sidekiq
    environment:
      DATABASE_URL: postgres://devuser:devpass@db:5432/backend_development
      REDIS_URL: redis://redis:6379/0
      RAILS_MASTER_KEY: 0ee296666c5c223a0aaa96e9e0b007fb
    depends_on:
      - db
      - redis
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "80:8080"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
